### PR TITLE
build for play 2.6 and scala 2.12

### LINKED ISSUE #8: Build for play 2.6 and scala 2.12
Hey @dylex, thanks for this lib!

[Play 2.6 is coming](https://github.com/playframework/playframework/releases/tag/2.6.0-M2), could you publish a build with scala 2.12?

### PR DESCRIPTION
**Pull request by cardamo**
fixes #8 
Hey @makslevental,
could you please publish this build to use with play 2.6

### CODE REVIEW

**Comment by makslevental** [comment]
@cardamo what does that entail? do you mean just merge in this PR?

**Comment by cardamo** [comment]
May be before merging it's better to bump version and change readme (I can do that in this pr).
But the most important thing is to publish a new artifact after merge.

**Comment by makslevental** [comment]
@cardamo publish where? i don't think this module is being used in our stack anymore so i'm not sure what you mean. if you need me to merge this in so that you can keep using that's fine but as far as i know we're not maintaining this anymore.

**Comment by cardamo** [comment]
Publish to oss.sonatype.org repository by executing `sbt publish` (Assuming the right credentials are set).
I may just copy all three source files to my project, but I think It's quite useful library and more people will need it as they upgrade to Play 2.6.

**Comment by jeep87c** [comment]
I agree with @cardamo, it's a useful library. In fact I'm also using it for my own APIs under Play!

Thanks @cardamo for your great work, I was about to fork it myself and do the update. Can't wait to get this published. Did you ensure there was no dependency conflicts?

Don't forget to properly update the README and bump the version to probably 0.6.1 since it's not a minor update.

Again, thanks for your work.

**Comment by makslevental** [comment]
@jeep87c @cardamo i do not have a scala dev environment set up (nor am i a scala dev). either of you are more than welcome to fork and takeover maintenance.

**Comment by jeep87c** [comment]
I leave it to @cardamo since he already did the latest fixes.

Please let us know once it's published.

**Comment by cardamo** [comment]
I'll try to publish at and report back

**Comment by makslevental** [comment]
@cardamo @jeep87c if one of you would like to take over i can transfer ownership

**Comment by cardamo** [comment]
I've publish a milestone to my bintray repo.
```
    resolvers += Resolver.bintrayRepo("cardamo", "com.cardamo.play-logback-access"),
    libraryDependencies += "org.databrary" %% "play-logback-access" % "0.6-m1"
```
going to publish a release (0.6) to jcenter

@makslevental I'd like to maintain the library so you can transfer access to me.

**Comment by makslevental** [comment]
@cardamo 

>cardamo/play-logback-access already exists and You can only transfer a repository from an organization to yourself at this time

i don't know if i'll be able to transfer to you without transferring to myself first but i know i won't be able to if you still have the fork

**Comment by cardamo** [comment]
@makslevental ok, I've deleted the fork

**Comment by makslevental** [comment]
@cardamo transfer request submitted

**Comment by cardamo** [comment]
@makslevental I've tried to confirm but it's already to late. Could you repeat transfer request please?

**Comment by makslevental** [comment]
@cardamo transfer request submitted

**Pull request closed without merging**
